### ISSUE TITLE
GenericLinuxWithDiscovery.json does not load in SPP

### ISSUE THREAD

**Issue by petrsnd** [OneIdentity/SafeguardCustomPlatform#34]
If you try to add a custom platform using the discovery sample it fails.

![image](https://user-images.githubusercontent.com/3847897/121755984-e3957600-cad5-11eb-9532-4588e17e3dc8.png)

I have tested with 6.9 and 6.10.  Fails on both.

**Comment by RobertCroteau** [comment]
Fixed in
https://github.com/OneIdentity/SafeguardCustomPlatform/pull/35
