### ISSUE TITLE
error sending command

### ISSUE THREAD

**Issue by Vinicius-Santos-Guedes** [OneIdentity/SafeguardCustomPlatform#38]
when I try to send the username and password to make the connection, it does not send the information (does not skip the line/press enter).

![Image1](https://user-images.githubusercontent.com/57989839/133844307-799dd83b-e380-42bb-920e-26583e5552b1.png)

![Image2](https://user-images.githubusercontent.com/57989839/133844338-c36ccef9-3970-40f3-961b-c6f0a519ebe4.png)

Would there be any way to send the Send command in another way or send the enter input?

**Comment by MiriamMcMahon** [comment]
@Vinicius-Santos-Guedes I suspect that your platform script is sending the credentials before the remote end has actually prompted for them.  The script is executed as an interactive shell session, so it must respond to the output from the remote server, otherwise it will get out of sync. 
I recommend the following (note that you will need to replace the strings in ExpectRegex()  to match the prompts that are produced by the host that you are testing.

    {
      "Name": "ConnectTelnet",
      "Parameters": [ { "ConnectUsername":{"Type":"String" }},
                      { "ConnectPassword":{"Type":"Secret" }}
      ],
      "Do":[
        { "Status": { "Type": "Connecting", "Percent":30,
          "Message":{"Name":"AssetConnectingWithAddress","Parameters":["%AssetName%","%Address%"]}}},
        { "Try" : { "Do":[
              {
                "Connect":{
                  "ConnectionObjectName":"Global:TelnetConnection",
                  "Type":"Telnet",
                  "Port":"%Port%",
                  "NetworkAddress":"%Address%",
                  "Login":"%ConnectUsername%",
                  "Timeout":"%Timeout%"} },
              { "Comment":{"Value":"Wait for login prompt"}},
              { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":5000, "ExpectRegex":"login:"}},
              { "Comment":{"Value":"Respond to login prompt"}},
              { "Send":{"ConnectionObjectName":"TelnetConnection","Buffer":"%ConnectUsername%"}},
              { "Comment":{"Value":"Wait for password prompt"}},
              { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":5000, "ExpectRegex":"Password:"}},
              { "Comment":{"Value":"Respond to password prompt"}},
              { "Send":{"ConnectionObjectName":"TelnetConnection","Buffer":"%ConnectPassword%", "ContainsSecret":true}},
              { "Comment":{"Value":"Flush any login welcome text before running any commands"}},
              { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":5000, "ExpectRegex":"(>|#) .*$"}}
            ],
            "Catch":[ { "Throw":{"Value": "Unable to connect: %Exception::$%"} } ] }
        }
      ]
    }

**Comment by Vinicius-Santos-Guedes** [comment]
@MiriamMcMahon ,
we use ExpectRegex() to match the prompts obtained by the host, but we don't get the password, even though we wait a longer time.
Would you have any idea, how to solve this?

he couldn't get the "Password:"
https://drive.google.com/file/d/1uQqagnxA34-YQ3E1QyGJCGDY6MkfV_8s/view?usp=sharing

https://drive.google.com/file/d/1kG_0LDIuVZuAmEKKF85DvsGWR-KoYKZj/view?usp=sharing

Example response using PuTTY
https://drive.google.com/file/d/1s51JkMwXswikaFWOLMwG4wAme8whVOS6/view?usp=sharing


Mycode
`
    {
      "Name": "ConnectTelnet",
      "Parameters": [ { "ConnectUsername": { "Type": "String" } },
                      { "ConnectPassword": { "Type": "String" } }
      ],
      "Do": [ { "Status": { "Type": "Connecting", 
                      "Percent": 30,
                      "Message": { "Name": "AssetConnectingWithAddress", "Parameters": [ "%AssetName%", "%Address%" ] } } },
              { "Try": { "Do": [ { "Connect": { "ConnectionObjectName": "Global:TelnetConnection",
                                          "Type": "Telnet",
                                          "Port": "%Port%",
                                          "NetworkAddress": "%Address%",
                                          "Login": "%ConnectUsername%",
                                          "Timeout": "%Timeout%" } },

                                          { "Comment":{"Value":"Wait for login prompt"}},
                                          { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":15000, "ExpectRegex":"login:"}},
                                          { "Comment":{"Value":"Respond to login prompt"}},
                                          { "Send":{"ConnectionObjectName":"TelnetConnection","Buffer":"%ConnectUsername%"}},
                                          { "Comment":{"Value":"Wait for password prompt"}},
                                          { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":60000, "ExpectRegex":"password:"}},
                                          { "Comment":{"Value":"Respond to password prompt"}},
                                          { "Send":{"ConnectionObjectName":"TelnetConnection","Buffer":"%ConnectPassword%", "ContainsSecret":true}},
                                          { "Comment":{"Value":"Flush any login welcome text before running any commands"}},
                                          { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":15000, "ExpectRegex":"(>|#) .*$"}},
`

**Comment by MiriamMcMahon** [comment]
The telnet comms log shows the text received by RSMS.  For the password prompt, it appears to be getting : “P@ssw0rd”

 
![image](https://user-images.githubusercontent.com/4605173/133448322-9582af2a-4b3b-4311-b25d-a89e0e555d53.png)


I suggest changing the second receive to

              { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":5000, "ExpectRegex":"(?i)(p.ssw.rd:*)" }},
              { "Condition" : {
                "If":"!Regex.IsMatch(ReturnStatus, \"(?i)(p.ssw.rd:*)\")",
                "Then":{ "Do":[ { "Throw": { "Value": "Did not get a password prompt"} }]}}
              },

**Comment by Vinicius-Santos-Guedes** [comment]
he is receiving is my host's password.

the error with your example code:
https://drive.google.com/file/d/1AxxjJxXVNMMaUSx1HvgUIyq6Ip61YXJ_/view?usp=sharing

**Comment by MiriamMcMahon** [comment]
@Vinicius-Santos-Guedes  It is difficult to diagnose the issue without being able to reproduce it. You  appear to be running "Microsoft Telnet Service" on windows - what version of windows is that service running on?  I am struggling to find a windows host with this feature available. From what I can see the MS telnet server has been removed from windows 10 and windows 2012 r2. I can only test on windows 10 with a third party telnet server.

Try the following to see if it provides any more information. Setting the TerminalType may help resolve any terminal issues. Setting the EndOfLineSuffix may help if the remote end is waiting for windows -style line endings.

    {
      "Name": "ConnectTelnet",
      "Parameters": [ { "ConnectUsername":{"Type":"String" }},
                      { "ConnectPassword":{"Type":"Secret" }}
      ],
      "Do":[
        { "Status": { "Type": "Connecting", "Percent":30,
          "Message":{"Name":"AssetConnectingWithAddress","Parameters":["%AssetName%","%Address%"]}}},
        { "Try" : { "Do":[
              {
                "Connect":{
                  "ConnectionObjectName":"Global:TelnetConnection",
                  "Type":"Telnet",
                  "Port":"%Port%",
                  "NetworkAddress":"%Address%",
                  "Login":"%ConnectUsername%",
                  "Timeout":"%Timeout%",
                  "TerminalType": "vt100",
                  "EndOfLineSuffix":"\r\n"
                } },
              { "Comment":{"Value":"Wait for login prompt"}},
              { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":5000, "ExpectRegex":"(?si)(login|username)"}},
              { "Log":{"Text": "TRACE: Login prompt:%{ReturnStatus}%"}},
              { "Comment":{"Value":"Respond to login prompt"}},
              { "Send":{"ConnectionObjectName":"TelnetConnection","Buffer":"%ConnectUsername%"}},
              { "Comment":{"Value":"Wait for password prompt"}},
              { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":5000, "ExpectRegex":"(?si)(p.ssw.rd)" }},
              { "Log":{"Text": "TRACE: Password prompt:%{ReturnStatus}%"}},
              { "Condition" : {
                "If":"!Regex.IsMatch(ReturnStatus, \"(?is)(p.ssw.rd)\")",
                "Then":{ "Do":[ { "Log": { "Text": "Did not get password prompt, GOT:%{ReturnStatus}%"} }]}}
              },
              { "Comment":{"Value":"Respond to password prompt"}},
              { "Send":{"ConnectionObjectName":"TelnetConnection","Buffer":"%ConnectPassword%", "ContainsSecret":true}},
              { "Comment":{"Value":"Flush any login welcome text before running any commands"}},
              { "Receive":{"ConnectionObjectName":"TelnetConnection","BufferName":"ReturnStatus", "ExpectTimeout":5000, "ExpectRegex":"(>|#) .*$"}},
              { "Log":{"Text": "TRACE: Login message :%{ReturnStatus}%"}}
            ],
            "Catch":[ { "Throw":{"Value": "Unable to connect: %Exception::$%"} } ] }
        }

**Comment by Vinicius-Santos-Guedes** [comment]
We were using Windows 2012 r2, when we switched our test to Linux Mint, it worked.
thanks for the clarification

**Comment by Vinicius-Santos-Guedes** [comment]
We were using Windows 2012 r2, when we switched our test to Linux Mint, it worked.
thanks for the clarification
