### ISSUE TITLE
Inconsistent behavior of the receive buffer in SSH

### ISSUE THREAD

**Issue by VVargaOI** [OneIdentity/SafeguardCustomPlatform#42]
Hi,
We recognized that the [LinuxApplicationTextConfig.json](https://github.com/OneIdentity/SafeguardCustomPlatform/blob/master/SampleScripts/SSH/LinuxApplicationTextConfig.json) script which worked before broke and nothing has changed in the environment but SPP.
The expected content of the receive buffer (except when a password prompt is shown) is "CHGPASS=0\nprompt" but sometimes it shows the prompt only, sometimes it's empty, sometimes it has the proper content.
Can you please help to resolve?
Thanks!
Viktor

**Comment by MiriamMcMahon** [comment]
@VVargaOI  It is possible that the timing within the receive has changed slightly with the new ssh library we use.  I have put up a PR with some suggested changes to the script that should help to keep the script in sync with the command output.   Please check that this script works for you.

**Comment by VVargaOI** [comment]
@MiriamMcMahon the changes made it, I tried the new script multiple times in my lab and works. Thanks a lot for your help!

**Comment by petrsnd** [comment]
More information about how receive works and a fix for the [LinuxApplicationTextConfig.json](https://github.com/OneIdentity/SafeguardCustomPlatform/blob/master/SampleScripts/SSH/LinuxApplicationTextConfig.json) script in pull request #43.
