### ISSUE TITLE
complete list/definition/schema of the custom platform JSON file

### ISSUE THREAD

**Issue by norielbernardo** [OneIdentity/SafeguardCustomPlatform#48]
Is there a complete list/definition/schema of the custom platform JSON file? more specifically, is there one that lists all of the reserved 'Parameter' names?

https://github.com/OneIdentity/SafeguardCustomPlatform/wiki/Writing-A-Custom-Platform-Script provides a list of SSH Parameters, but it's only a subset of the possible 36 parameter names.

**Comment by Kevin-Andrew** [comment]
@norielbernardo , while I don't know your exact intent, and I can't say for certain that the following is definitive, I was able to find this:
```
AccountDn,
AccountId,
AccountPassword,
AccountUserName,
Address,
ApplicationName,
AssetName,
CheckHostKey,
DelegationPrefix,
DiscoveryQuery,
DomainName,
EnablePassword,
EnableLevel,
FuncAccountDn,
FuncPassword,
FuncUserAccessKey,
FuncUserAccessKeyId,
FuncUserDomain,
FuncUserName,
FuncUserNetBiosName,
HostKey,
Instance,
NetbiosName,
ObjectSid,
NewPassword,
NewSshKey,
NewSshKeyComment,
NewSshPrivateKey,
NonPrivFunc,
OldSshKey,
PasswordAttribute,
Port,
SkipServerCertValidation,
Timeout,
UserKey,
UseSsl,
WorkstationId,
ClientId,
DependentUsername,
ChangeService,
ChangeTask,
DependentPassword,
RestartService,
PreemptAdmin,
ServiceDiscoveryQuery,
UseNamedPipe,
OraclePrivileges,
ChangeComPlus,
ChangeIis,
NewSshKeyType,
PrivilegedUser,
CloudConnectClientId,
CloudConnectClientSecret,
CloudConnectTokenEndpoint,
CloudConnectDiscoveryServiceAddress,
CloudConnectRegisteredConnectorId,
CloudConnectConnectServiceAddress,
TacacsSecret,
Interval,
ServiceName,
SkipPasswordEncryption,
HideAlterUserCommand,
AccountDiscoveredId,
SshPort,
ClientSecret,
ClientSecretId,
KeyLifetime
```

That's obviously more than 36, but the documentation is old and new features have been added. Again, it may not be 100% correct, or applicable to your end goal, but hopefully it gives you something to go off of.

**Comment by MiriamMcMahon** [comment]
@norielbernardo  @Kevin-Andrew 

You're correct - we havent been keeping this documentation up to date with the newer features. I have updated the list of reserved parameters that can be used in custom platform scripts https://github.com/OneIdentity/SafeguardCustomPlatform/wiki/Writing-A-Custom-Platform-Script , and I am working on updating the command reference.

**Comment by MiriamMcMahon** [comment]
The wiki documentation has been updated to describe the reserved parameters that can be used in a custom platform script . 
Note: custom platform scripts are only supported with the Scriptable platform module in RSMS.  The complete list of parameters described by Kevin above includes some parameters that are used  internally in RSMS and are not suitable for use in custom platforms.
