### ISSUE TITLE
Typo on 

### ISSUE THREAD

**Issue by Kevin-Andrew** [OneIdentity/SafeguardCustomPlatform#50]
On https://github.com/OneIdentity/SafeguardCustomPlatform/wiki/Writing-A-Custom-Platform-Script, down in the last paragraph is the following sentence that has the word `of`, when it should be `or`.

> Lastly, the script will need to indicate whether it succeeded **of** failed in its execution of the designated operation.

(emphasis mine).
![image](https://user-images.githubusercontent.com/22459191/217944988-64990b79-9985-499d-adc0-21a13e820c44.png)

**Comment by MiriamMcMahon** [comment]
@Kevin-Andrew  Thanks, I've updated the text
