### ISSUE TITLE
HTTP Verb Limitation

### ISSUE THREAD

**Issue by norielbernardo** [OneIdentity/SafeguardCustomPlatform#56]
https://github.com/OneIdentity/SafeguardCustomPlatform/wiki/Request mentions that only Get, Post, Put, and Delete is accepted as a Verb. I tried to use the verb PATCH as Oracle Fusion REST API expects a PATCH for updating users.

![image](https://github.com/OneIdentity/SafeguardCustomPlatform/assets/119979394/ed2ec7e0-a8ac-45e4-b613-5792c50da2e2)

Is there a way around this limitation?

**Comment by norielbernardo** [comment]
version 7.3 supports Patch HTTP request @MiriamMcMahon thanks

**Comment by MiriamMcMahon** [comment]
@norielbernardo Thanks -  I have updated the wiki to add the supported verbs in 7.3.
